"use client";

import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { formatIndianCurrency, formatDate, cn } from "@/lib/utils";
import { toast } from "sonner";
import { Trash2 } from "lucide-react";

export default function CCLedgerPage() {
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
  const utils = trpc.useUtils();

  const { data, isLoading } = trpc.cc.list.useQuery();
  const { data: dashData } = trpc.dashboard.getMetrics.useQuery();

  const deleteMutation = trpc.cc.delete.useMutation({
    onSuccess: () => {
      utils.cc.list.invalidate();
      setDeleteConfirmId(null);
      toast.success("CC entry deleted. Balances recalculated.");
    },
    onError: (err) => {
      toast.error(err.message || "Failed to delete CC entry");
    },
  });

  const currentBalance = data?.currentBalance ?? 0;
  const ccLimit = data?.ccLimit ?? 5000000;
  const available = data?.available ?? ccLimit;
  const utilizationPct = data?.utilizationPct ?? 0;

  /** Returns true if this is a manually created entry (not auto-generated by payment flow) */
  function isManualEntry(notes: string | null | undefined): boolean {
    if (!notes) return true;
    return !notes.startsWith("Auto:") && !notes.startsWith("Auto-reversed:");
  }

  return (
    <div>
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-[#1B4F72]">CC Ledger</h1>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <div className="bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 p-4">
          <p className="text-xs text-[#6C757D] uppercase tracking-wide font-medium mb-1">
            Current Balance
          </p>
          <p className="text-xl font-bold text-[#C0392B]">
            {formatIndianCurrency(currentBalance)}
          </p>
        </div>
        <div className="bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 p-4">
          <p className="text-xs text-[#6C757D] uppercase tracking-wide font-medium mb-1">
            Available
          </p>
          <p className="text-xl font-bold text-[#27AE60]">
            {formatIndianCurrency(available)}
          </p>
        </div>
        <div className="bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 p-4">
          <p className="text-xs text-[#6C757D] uppercase tracking-wide font-medium mb-1">
            CC Limit
          </p>
          <p className="text-xl font-bold text-[#2C3E50]">
            {formatIndianCurrency(ccLimit)}
          </p>
        </div>
      </div>

      {/* Utilization Bar + Money Trail */}
      <div className="bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 p-4 mb-6">
        <div className="flex items-center justify-between mb-2">
          <p className="text-sm font-medium text-[#2C3E50]">Utilization</p>
          <p className="text-sm font-bold text-[#2C3E50]">
            {utilizationPct.toFixed(1)}%
          </p>
        </div>

        {/* Stacked bar showing where CC money is */}
        {dashData?.cc.moneyTrail && currentBalance > 0 ? (() => {
          const trail = dashData.cc.moneyTrail;
          const total = currentBalance;
          const segments = [
            { label: "Stock", value: trail.stockAtCost, color: "bg-violet-500" },
            { label: "Collection", value: trail.soldAtCost, color: "bg-blue-500" },
            { label: "GST", value: trail.gstPaid, color: "bg-teal-500" },
            { label: "Transport", value: trail.transport, color: "bg-orange-400" },
            { label: "Advance", value: trail.overpaidToMills, color: "bg-gray-400" },
          ].filter(s => s.value > 0);

          return (
            <>
              <div className="w-full flex rounded-full h-4 overflow-hidden mb-3">
                {segments.map((seg) => (
                  <div
                    key={seg.label}
                    className={cn("h-4 transition-all", seg.color)}
                    style={{ width: `${Math.max((seg.value / total) * 100, 1)}%` }}
                    title={`${seg.label}: ${formatIndianCurrency(seg.value)} (${((seg.value / total) * 100).toFixed(0)}%)`}
                  />
                ))}
              </div>
              <div className="flex flex-wrap gap-x-4 gap-y-1.5">
                {segments.map((seg) => (
                  <div key={seg.label} className="flex items-center gap-1.5">
                    <span className={cn("w-2.5 h-2.5 rounded-full flex-shrink-0", seg.color)} />
                    <span className="text-[11px] text-[#6C757D]">{seg.label}</span>
                    <span className="text-[11px] font-semibold text-[#2C3E50]">
                      {formatIndianCurrency(seg.value)}
                    </span>
                    <span className="text-[10px] text-[#ADB5BD]">
                      ({((seg.value / total) * 100).toFixed(0)}%)
                    </span>
                  </div>
                ))}
              </div>
            </>
          );
        })() : (
          <div className="w-full bg-[#DEE2E6] rounded-full h-4">
            <div
              className={cn(
                "h-4 rounded-full transition-all",
                utilizationPct > 80 ? "bg-[#C0392B]" : utilizationPct > 50 ? "bg-[#E67E22]" : "bg-[#27AE60]"
              )}
              style={{ width: `${Math.min(100, utilizationPct)}%` }}
            />
          </div>
        )}
      </div>

      {/* Loading Skeleton */}
      {isLoading && (
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 p-4 space-y-3 animate-pulse">
              <div className="flex items-center justify-between">
                <div className="h-3 bg-gray-200 rounded w-24" />
                <div className="h-6 bg-gray-200 rounded-full w-16" />
              </div>
              <div className="flex items-center justify-between">
                <div className="h-3 bg-gray-200 rounded w-16" />
                <div className="h-4 bg-gray-200 rounded w-28" />
              </div>
              <div className="flex items-center justify-between">
                <div className="h-3 bg-gray-200 rounded w-20" />
                <div className="h-4 bg-gray-200 rounded w-24" />
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Entries Table */}
      {!isLoading && data && data.entries.length > 0 && (
        <>
          {/* Desktop Table */}
          <div className="hidden md:block bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 overflow-hidden mb-6">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-[#F8F9FA] border-b border-[#DEE2E6]">
                  <th className="text-left px-4 py-3 font-semibold text-[#6C757D] text-xs uppercase tracking-wide">Date</th>
                  <th className="text-left px-4 py-3 font-semibold text-[#6C757D] text-xs uppercase tracking-wide">Event</th>
                  <th className="text-right px-4 py-3 font-semibold text-[#6C757D] text-xs uppercase tracking-wide">Amount</th>
                  <th className="text-right px-4 py-3 font-semibold text-[#6C757D] text-xs uppercase tracking-wide">Running Balance</th>
                  <th className="text-right px-4 py-3 font-semibold text-[#6C757D] text-xs uppercase tracking-wide">Days</th>
                  <th className="text-right px-4 py-3 font-semibold text-[#6C757D] text-xs uppercase tracking-wide">Interest</th>
                  <th className="text-left px-4 py-3 font-semibold text-[#6C757D] text-xs uppercase tracking-wide">Notes</th>
                  <th className="px-4 py-3 w-12"></th>
                </tr>
              </thead>
              <tbody>
                {data.entries.map((entry) => (
                  <tr key={entry.id} className="border-b border-gray-100 hover:bg-[#F8F9FA]">
                    <td className="px-4 py-3 text-[#2C3E50]">{formatDate(entry.date)}</td>
                    <td className="px-4 py-3">
                      <span
                        className={cn(
                          "px-2.5 py-1 rounded-full text-xs font-semibold border",
                          entry.event === "Draw"
                            ? "bg-[#FADBD8] text-[#922B21] border-[#E74C3C]"
                            : "bg-[#D5F5E3] text-[#1E8449] border-[#27AE60]"
                        )}
                      >
                        {entry.event}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-right font-medium text-[#2C3E50]">
                      {formatIndianCurrency(entry.amount)}
                    </td>
                    <td className="px-4 py-3 text-right font-medium text-[#C0392B]">
                      {formatIndianCurrency(entry.runningBalance)}
                    </td>
                    <td className="px-4 py-3 text-right text-[#6C757D]">{entry.days}</td>
                    <td className="px-4 py-3 text-right text-[#6C757D]">
                      {formatIndianCurrency(entry.interest)}
                    </td>
                    <td className="px-4 py-3 text-[#6C757D]">
                      {entry.notes?.startsWith("Auto:") || entry.notes?.startsWith("Auto-reversed:") ? (
                        <span className="inline-flex items-center gap-1.5">
                          <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-[#EBF5FB] text-[#2980B9] border border-[#AED6F1]">
                            AUTO
                          </span>
                          <span title={entry.notes.replace(/^Auto:\s*/, "").replace(/^Auto-reversed:\s*/, "")}>
                            {(() => { const t = entry.notes.replace(/^Auto:\s*/, "").replace(/^Auto-reversed:\s*/, ""); return t.length > 30 ? t.slice(0, 30) + "..." : t; })()}
                          </span>
                        </span>
                      ) : (
                        entry.notes ? (
                          <span title={entry.notes}>{entry.notes.length > 30 ? entry.notes.slice(0, 30) + "..." : entry.notes}</span>
                        ) : "-"
                      )}
                    </td>
                    <td className="px-4 py-3">
                      {isManualEntry(entry.notes) && (
                        <button
                          onClick={() => setDeleteConfirmId(entry.id)}
                          className="p-1.5 text-[#ADB5BD] hover:text-[#E74C3C] transition-colors rounded-lg hover:bg-red-50"
                          title="Delete entry"
                        >
                          <Trash2 size={15} />
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Mobile Cards */}
          <div className="md:hidden space-y-3 mb-6">
            {data.entries.map((entry) => (
              <div
                key={entry.id}
                className="bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 p-4"
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-[#6C757D]">{formatDate(entry.date)}</span>
                  <div className="flex items-center gap-2">
                    <span
                      className={cn(
                        "px-2.5 py-1 rounded-full text-xs font-semibold border",
                        entry.event === "Draw"
                          ? "bg-[#FADBD8] text-[#922B21] border-[#E74C3C]"
                          : "bg-[#D5F5E3] text-[#1E8449] border-[#27AE60]"
                      )}
                    >
                      {entry.event}
                    </span>
                    {isManualEntry(entry.notes) && (
                      <button
                        onClick={() => setDeleteConfirmId(entry.id)}
                        className="p-1.5 text-[#ADB5BD] hover:text-[#E74C3C] transition-colors rounded-lg hover:bg-red-50"
                        title="Delete entry"
                      >
                        <Trash2 size={15} />
                      </button>
                    )}
                  </div>
                </div>
                <div className="flex items-center justify-between mb-1">
                  <span className="text-sm text-[#6C757D]">Amount</span>
                  <span className="font-semibold text-[#2C3E50]">
                    {formatIndianCurrency(entry.amount)}
                  </span>
                </div>
                <div className="flex items-center justify-between mb-1">
                  <span className="text-sm text-[#6C757D]">Balance</span>
                  <span className="font-semibold text-[#C0392B]">
                    {formatIndianCurrency(entry.runningBalance)}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-[#6C757D]">Interest ({entry.days}d)</span>
                  <span className="text-sm text-[#6C757D]">
                    {formatIndianCurrency(entry.interest)}
                  </span>
                </div>
                {entry.notes && (
                  <p className="text-xs text-[#ADB5BD] mt-2">
                    {entry.notes.startsWith("Auto:") || entry.notes.startsWith("Auto-reversed:") ? (
                      <span className="inline-flex items-center gap-1.5">
                        <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-[#EBF5FB] text-[#2980B9] border border-[#AED6F1]">
                          AUTO
                        </span>
                        <span>{entry.notes.replace(/^Auto:\s*/, "").replace(/^Auto-reversed:\s*/, "")}</span>
                      </span>
                    ) : (
                      entry.notes
                    )}
                  </p>
                )}
              </div>
            ))}
          </div>

          {/* Interest Summary */}
          <div className="bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 p-4">
            <h3 className="text-sm font-semibold text-[#2C3E50] mb-3 uppercase tracking-wide">
              Interest Summary
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div>
                <p className="text-xs text-[#6C757D] mb-1">Calculated Interest</p>
                <p className="text-lg font-bold text-[#2C3E50]">
                  {formatIndianCurrency(data.calculatedInterestTotal)}
                </p>
              </div>
              <div>
                <p className="text-xs text-[#6C757D] mb-1">Actual Interest (PNB)</p>
                <p className="text-lg font-bold text-[#2C3E50]">
                  {formatIndianCurrency(data.actualInterestTotal)}
                </p>
              </div>
              <div>
                <p className="text-xs text-[#6C757D] mb-1">Difference</p>
                <p
                  className={cn(
                    "text-lg font-bold",
                    data.interestDifference > 0
                      ? "text-[#C0392B]"
                      : data.interestDifference < 0
                        ? "text-[#27AE60]"
                        : "text-[#2C3E50]"
                  )}
                >
                  {data.interestDifference > 0 ? "+" : ""}
                  {formatIndianCurrency(data.interestDifference)}
                </p>
              </div>
            </div>
          </div>
        </>
      )}

      {/* Empty State */}
      {!isLoading && data && data.entries.length === 0 && (
        <div className="bg-white rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.08)] border border-gray-200 p-8 text-center">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 mx-auto text-[#ADB5BD] mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>
          <h3 className="text-lg font-semibold text-[#2C3E50] mb-2">No CC entries yet</h3>
          <p className="text-[#6C757D] mb-2 text-sm">
            CC entries are created automatically when you record payments via CC.
          </p>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteConfirmId && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl p-6 max-w-sm w-full shadow-lg">
            <h3 className="text-lg font-semibold text-[#2C3E50] mb-2">
              Delete CC Entry
            </h3>
            <p className="text-[#6C757D] mb-3">
              Are you sure you want to delete this CC entry?
            </p>
            <div className="bg-[#FEF9E7] border border-[#F1C40F] rounded-xl px-4 py-3 mb-6">
              <p className="text-sm text-[#7D6608] font-medium">
                All running balances and interest calculations will be recalculated. This cannot be undone.
              </p>
            </div>
            <div className="flex gap-3 justify-end">
              <button
                onClick={() => setDeleteConfirmId(null)}
                className="min-h-[48px] px-4 py-3 text-base font-semibold text-[#6C757D] bg-[#F8F9FA] rounded-xl hover:bg-gray-200 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={() => deleteMutation.mutate({ id: deleteConfirmId })}
                disabled={deleteMutation.isPending}
                className="min-h-[48px] px-4 py-3 text-base font-semibold text-white bg-[#E74C3C] rounded-xl hover:bg-[#C0392B] transition-colors disabled:opacity-50"
              >
                {deleteMutation.isPending ? "Deleting..." : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
